# Headless Service

apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: linkding-2
spec:
  clusterIP: None
  selector: { app: postgres }
  ports:
    - port: 5432

---

# StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: linkding-2
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels: { app: postgres }
  template:
    metadata:
      labels: { app: postgres }
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom: { secretKeyRef: { name: linkding-db, key: username } }
            - name: POSTGRES_PASSWORD
              valueFrom: { secretKeyRef: { name: linkding-db, key: password } }
            - name: POSTGRES_DB
              valueFrom: { secretKeyRef: { name: linkding-db, key: database } }
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "linkding"]
            initialDelaySeconds: 5
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
