apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pods
  name: nginx-pods
spec:
  containers:
  - image: nginx
    name: nginx-pods
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
