apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: homarr
stringData:
  db-encryption-key: "67d5d8ea2296696668de1cee6909d520f572746addc2a333c6e4f89ef6e8e9ec"
  db-url: "mysql://homarr:wisedeveloper8@homarr-mysql:3306/homarr"
  mysql-password: "wisedeveloper8"
  mysql-root-password: "wisedeveloper8"
